### ISSUE TITLE
Favorite里面的照片流功能

### ISSUE THREAD

**Issue by ghost** [JamesPan/blog-src#1]
可以请问一下您博客Favorite那一栏里面的照片流功能是怎么实现的吗？我把image-stream.js文件复制过来了，但是图片还是出不来，只有白框和下面的文字，图片路径没有问题。谢谢了

**Comment by jamespan** [comment]
@alexwan2011 你目前提供的信息不足以支持我做判断。

首先确认你使用博客生成器是 Hexo，然后确认 image-stream.js 在主题中的相对路径和我这边的一致。

检查你对 stream 标签的用法是否和 https://raw.githubusercontent.com/JamesPan/blog-src/master/source/favorite/index.md 一致。

如果图片还是无法显示，提供 Chrome 开发者工具控制台报错信息截图，或许我能帮助你发现一些什么。

**Comment by ghost** [comment]
@JamesPan 对的，我用的是hexo，主题也是icarus。image-stream.js的也是放在了icarus/scripts下面。stream的用法是参考您那个文件来写的，检查了也没有问题。
不知道方不方便直接看我的源文件帮我检查一下呢？我的博客是http://alexwan2011.github.io  ,生成的文件在https://github.com/alexwan2011/alexwan2011.github.io ,源文件不知道什么情况在这台电脑push不上来。
谢谢

**Comment by jamespan** [comment]
@alexwan2011 

没有引用jquery。仿照 https://github.com/JamesPan/blog-src/blob/master/themes/icarus/layout/_partial/head.ejs#L59 引用一下就好了。

没想到默认的icarus没有引用jquery。

**Comment by ghost** [comment]
@JamesPan 恩恩，已经解决了！刚刚看了下默认的确实没有引用，没想到是这个问题。多谢多谢:)
