### ISSUE TITLE
请问旧的博客还能看吗？

### ISSUE THREAD

**Issue by lizebang** [JamesPan/blog-src#2]
@JamesPan 你好，今天我访问 https://blog.jamespan.me/ 发现它更换了主题，不知道旧的博客还能看吗？如果不能看了，真的太可惜了。

**Comment by lizebang** [comment]
@JamesPan ...额，看了一下才发现，这个就是存档，打扰了...

**Comment by jamespan** [comment]
@lizebang 之前的博客内容在https://github.com/JamesPan/gravbox/tree/mod/content/user/pages/01.posts ，要找啥内容全文搜索一下还是可以的，我有力气了会把之前的博文迁移到现在的博客上，最近懒

**Comment by lizebang** [comment]
@JamesPan 十分感谢
